# Generated by Django 3.0.6 on 2020-07-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodBankWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='bullsit', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
